first try
argoneen1/java-explore-with-me pull request #1
Opened 2022-12-04 12:14 UTC by argoneen1

2022-12-07 06:20 UTC, eugene-lenkevich requested changes
Привет, Александр, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай в слаке, не стесняйся, немножко допилить осталось :)

Из основного. 
Смотрю ты использовал кучу продвинутых вещей, при выполнении этой работы, это очень круто, однако не надо переоценивать разработчиков которые потом будут поддерживать этот код. Очень легко скатиться в оверинжиниринг и слелать слишком сложными те вещи, которые могли бы быть простыми. Вообще, код пишется не для компьютера, код пишется для разработчика, который этот код потом будет поддерживать и нет ничего зазорного в том чтобы код был линейным и примитивным. Это даже очень хорошо, при условии если он это делает это правильно и укладывается в показатели по производительности. 
Вообще, можно посчитать сколько денег тратит команда разработчиков за месяц (зарплаты можно глянуть на хх, добавить сверху +40% налогов, плюс отпуска и больничные), держать это в голове и писат код, исходя из того, насколько он легко поддерживается в первую очерель, в случае чего новую ноду в кластер засунуть гораздо проще. В общем лучше избегать оверинжиниринга, хоть, соргласен, часто это очень интересно покопаться в этом всем :)
Я отметил те места которые стоит поправить

Удачи!

2022-12-07 06:20 UTC, eugene-lenkevich commented on config/src/main/java/ru/practicum/ewm/Configuration.java
> +@org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Configuration;
..
@Configuration

Зачем нам тут этот пакет, давай его просто ипортируем и не будет лишних символов :)

2022-12-07 06:20 UTC, eugene-lenkevich commented on main/src/main/java/ru/practicum/ewm/ExploreWithMeMain.java
> +    public StatsClient getStatsWebClient(
Тут не очень очевидное место нахождения конфигурации, думаю лучше поместить в отдельный пакет для конфигураций в виде отдельного файла с классом, отмеченным @Configuration

Пример у тебя уже есть, для форматов дат. И, кстати, ту конфигурацию в этот же пакет можно сложить. Все будет в одном месте, искать потом проще

Можно еще назвать соответствующе

JacksonConfig
StatsClientConfig

:)
DateSerializationConfig

2022-12-07 06:20 UTC, eugene-lenkevich commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @Transient
Ммм, в сущности есть ссылка на web-клиент, пусть и @Transient, да и сама сущность бин... ой не, это поперек парадигмы спринга. У сущности и у бина совершенно разный жизненный цикл, плюс как это себя поведет когда сущностей у нас станет очень много (клиенты массово поломятся с запросами). Я предположу что сильная просадка по производительности гарантирована плюс кучка неочевидных проблем с кэшированием всего этого дела. Начнем с того что спринговый бин в такм виде singleton, то есть один инстанс на всех, как минимум надо делать prototype :)

https://www.baeldung.com/spring-bean-scopes

В общем выглядит как очень спорное решение, лучше все же разделить сущность и бины. То есть, в сервисе мы достаем сущности из БД, например, перекладываем в dto, дообогащаем данными от клиента, возвращаем в контроллер :)

Предположу что ты хотело пофиксить вот этот момент
https://habr.com/ru/post/346016/

но не, так оно в спринге не уверен что взлетит, явно требует дополнительного ресерча, и, в общем то, не для учебного проекта :)

2022-12-07 06:20 UTC, eugene-lenkevich commented on main/src/main/java/ru/practicum/ewm/user/UserRepository.java
> +    @Query("select new ru.practicum.ewm.user.dto.UserDto(u.id, u.name, u.email) from User u")
А не проще  было б доставать сущности и не заморачиваться. Потом потребуется добавить еще одно поле, придеться все переделывать. Плюс как будет работать кэширование, как будут работать оптимитстичные и пессимистичные блокировки, скорее всего никак и мы потом, когда будем уже давно в продакшене, у нас будет много пользователей и высокая нагрузка, получим проблемы с поддержкой. 

https://habr.com/ru/post/434836/

Вообще выглядить больше как преждевременная оптимизация

https://dzen.ru/media/codeblog/prejdevremennaia-optimizaciia-5c69d4c0e4bead00af906943


Такое имеет смысл делать в случае, когда у нас есть какой-то сложный запрос, который возвращает  аггрегацию на основе нескольких таблиц и под это, соотвественно, нет смысла заводить отдельную сущность. Тогда мы просто в dto перекладываем результат и все

2022-12-07 06:20 UTC, eugene-lenkevich commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @Formula("(SELECT COUNT(pr.event_id) FROM participation_requests AS pr WHERE pr.event_id = id)")
Я бы очень поостерегся так делать :)
Потом, годика так через три когда никто уже этого помнить не будет, кто то возмет выгрузит громадную коллекцию сущностей (для месячного отчета, например) и проитерируется по ним. В итоге получит N-count запросов, которые не очень быстро обычно выполняются и положат БД. 
В общем такой момент, очень скользкий, мне кажется лучше сделать явный запрос, плюс, в случае, если сущностей будет несколько, то можно обойтись одним запросом с group by :)

2022-12-07 06:20 UTC, eugene-lenkevich commented on statistics/statistics-server/src/main/java/ru/practicum/statservice/Controller.java
> +    private final StatsRepository repository;
Сразу репозиторий в контроллер инжектишь, без сервиса :)

Ну лан, так можно делать, потому что тут особо логики то и нет, чисто достать данные из БД и отдать на фронт

2022-12-07 06:20 UTC, eugene-lenkevich commented on statistics/statistics-server/src/main/java/ru/practicum/statservice/model/Hit.java
> +    private InetAddress ip;
А не проще было просто как строку хранить? :)
В общем то в том что в БД хрняться не очень то валидные всетевые имена ничего стращного нет, никто не знает как потом поменяется бизнес-логика, а тут мы еще получаем дополнительный гимор с глубоким копированием, функция которого обрабатывает какие то сетевые ошибки, это не очевидно все :)

2022-12-07 06:20 UTC, eugene-lenkevich commented on statistics/statistics-server/src/main/java/ru/practicum/statservice/hibernate/PgInetType.java
> +    public Object deepCopy(Object value) {
Вообще, самый простой способ глубокого копирования - сериализовать в json потом десериализовать обратно :)

2022-12-08 15:57 UTC, argoneen1 commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @Formula("(SELECT COUNT(pr.event_id) FROM participation_requests AS pr WHERE pr.event_id = id)")
Нормально реализовать запрос с group by я не смог, но getConfirmedRequest вынес в ParticipationRequestService

2022-12-08 17:20 UTC, eugene-lenkevich commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @Formula("(SELECT COUNT(pr.event_id) FROM participation_requests AS pr WHERE pr.event_id = id)")
Норм, пусть так будет

2022-12-08 17:23 UTC, eugene-lenkevich requested changes
Спасибо за доработку, ну вроде все норм, единственное вот эта аннотация осталась забытой, ее бы почикать :)

PS вообще, конечно, дипломной работой впечатлен, ее оригинальностью и нестандартностью некоторых решений ;)

![image](https://user-images.githubusercontent.com/94845100/206520604-dcafb80b-e4bb-4e9f-9bcb-3981aeba0db8.png)

2023-01-13 04:51 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-01-18 17:23 UTC, merged